[workspace]
resolver = "2"

members = [
    "suffixtree",
    "suffixarray",
    "tsv-utils",
    "libsais64-rs",
    "suffixarray_server",
    "suffixarray_builder",

    "fa-compression",
    "sa-mappings"
]
