//! The `fa-compression` crate provides multiple algorithms for compressing and decompressing
//! functional annotations. The algorithms are designed to work with the output generated by the
//! Unipept index builder.

#![warn(missing_docs)]

pub mod algorithm1;
pub mod algorithm2;
