[package]
name = "suffixarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdivsufsort = "2.0.0"
divsufsort = "2.0.0"
