[package]
name = "suffixarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdivsufsort = "2.0.0"
clap = { version = "4.4.8", features = ["derive"] }
divsufsort = "2.0.0"
get-size = "0.1.4"
libdivsufsort-rs = "0.1.0"
tsv-utils = { path = "../tsv-utils"}
umgap = "1.0.0"
