#!/bin/bash

#########################################################################################################
### This script is designed to run on the Ghent university HPC                                        ###
###                                                                                                   ###
### how to use:                                                                                       ###
### 1) load the rust module Rust/1.70.0-GCCcore-12.3.0 with `module load Rust/1.75.0-GCCcore-12.3.0`  ###
### 2) compile the code on the login node using `cargo build --release`                               ###
### 3) navigate the to folder of the binary (in `target/release`)                                     ###
### 4) submit the job to the queue with `qsub suffix_array.pbs`                                       ###
#########################################################################################################

# go to cluster with high memory
module swap cluster/gallade

# define requested memory, cpu resources and email notifications
#PBS -m abe
#PBS -l walltime=06:30:00
#PBS -l mem=920gb
# ask for 1 node, 1 cpu (not more needed since we don't have parallelism)
#PBS -l nodes=1:ppn=1
#PBS -N suffix_array_construction_uniprot

# define output and error files
#PBS -o stdout.$PBS_JOBID
#PBS -e stderr.$PBS_JOBID

#folder="swissprot_var1/"
#prefix="$VSC_DATA/BenchmarkData/"
# search_file="search_file_no_mch.tsv"

folder=""
prefix="$VSC_DATA_VO/bram/"

# load Rust
module load Rust/1.75.0-GCCcore-12.3.0
module load Clang/16.0.6-GCCcore-12.3.0 # needed to build the bindings from Rust to C

# go to current working dir and execute
cd $PBS_O_WORKDIR

# compile
cargo build --release

# execute
./suffixarray -d "$prefix""$folder"uniprotKB_protein_database.tsv -t "$prefix"taxons.tsv --build-only --suffix-to-protein-mapping sparse -o "$prefix"uniprot_indexed
# ./suffixarray -d "$prefix""$folder"protein_database.tsv -s "$prefix""$folder""$search_file" -t "$prefix"taxons.tsv -m all-occurrences