[package]
name = "fm-index-unipept"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tsv-utils = { path = "../tsv-utils"}
clap = { version = "4.4.8", features = ["derive"] }
fm-index = "0.1"

