[package]
name = "libsais64-rs"
version = "0.1.0"
edition = "2021"
build = "builder.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.4"
